
server:
  port: 9090
#  config to connect to the database
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            jwk-set-uri: http://localhost:8080/realms/springboot/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot

  application:
    name: spring-boot-restful-api
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 123 # your password of postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    validate file size
  servlet:
    multipart:
      max-request-size: 1MB # size of files users can request from api
      max-file-size: 1MB #files size that users able to upload

file:
  upload-location: D:\\Multi-programming_languages\\Spring boot\\spring-boot-short-course\\restful-api-001\\uploads
  preview-path: localhost:9090/uploads/
  download-path: localhost:9090/

#keycloak info config
keycloak:
  server-url: http://localhost:8080
  main-realm: springboot
  client-id: spring-boot
  client-secrete: NXAC1RTiuI0eSNWCU4eAUIqFUaUC5ZfK

